name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Install dependencies
        uses: go mod download

      - name: Run tests
        uses: go test ./...

      - name: Build application
        run: go build -o pizza-auth ./cmd/main.go

  deploy:
    needs: build
    runs-on: ubuntu-latest

